keywords = {'beach_wedding_wedding': ['Wedding Dress', 'Ceremony', 'bride', 'Dancing', 'bride getting ready',
                        'groom getting ready', 'Table Setting', 'Flowers', 'decorations', 'family',
                        'baby', 'kids', 'mother', 'father', 'Romance', 'affection', 'Intimacy',
                        'Happiness', 'Holding hands', 'smiling', 'Hugging', 'Kissing', 'Ring', 'Veil'],
            'indoor_venue_wedding': ['Couple', 'Pregnancy', 'Belly', 'affection', 'joy', 'Family', 'face', 'body'],
            'backyard_garden_sequence': ['faces', 'party', 'smiling', 'affection', 'indoor', 'outdoor', 'dark', 'food', 'hugging',
                      'music', 'performance', 'speech', 'wine', ],
            'gay_sequence': ['Parents', 'children', 'generations', 'love', 'happiness', 'hugging', 'kissing',
                       'holding hands', 'joy', 'affection', 'caring', 'Baby', 'kids', 'game', 'book',
                       'yard', 'home', 'indoor', 'outdoor', 'bedroom', 'kitchen', 'living room',
                       'ball', 'doll', 'car', 'celebration'],
            'desert_sequence': ['mother', 'father', 'trolly', 'yard', 'bedroom', 'outdoor', 'indoor', 'bodysuit',
                             'diaper', 'Sleepsuits', 'footed pajama', 'sleep', 'hat', 'cap', 'smile'],
            'normal_sequence': ['outdoor', 'indoor', 'academic cap', 'mortarboard', 'diploma', 'graduation gown',
                       'parents', 'hood', 'stole', 'ceremony']}
