category_queries = {
    'bride and groom': ['bride and groom', ],
    'bride party': ['bride and brides maids', ],
    'groom party': ['groom and best men', ],
    'full party': ['bride and groom with bride maids and best men', ],
    'settings': ['table setting', 'decor', ],
    'flowers': ['flowers', 'flower bouquet', ],
    'food': ['food', ],
    'bride getting dressed': ['bride getting dress', ],
    'getting hair-makeup': ['getting hair done', 'getting makeup done', ],
    'accessories': ['jewelry', 'cufflinks', 'perfume', 'belt'],
    'shoes': ['shoes', ],
    'wedding dress': ['wedding dress', ],
    'suit': ['suit', ],
    'pet': ['pet'],
    'invite': ['invite'],
    'rings': ['rings'],
    'dancing': ['dancing'],
    'cake cutting': ['cake cutting', 'bride and groom cut a cake', ],
    'speech': ['speech', ],
    'pool': ['poo', ],
    'ceremony': ['ceremony', 'wedding ceremony', ],
    'walking the aisle': ['walking the aisle', ],
    'tattoo': ['tattoo'],
    'portrait': ['portrait', 'headshot', ],
    'very large group': ['very large group of people', ],
    'kiss': ['bride and groom kiss', ],
    'limo-vehicle': ['vehicle', 'limousine', ],
    'inside limo-vehicle': ['inside limousine', 'inside car', 'inside vehicle'],
    'entertainment': ['band', 'show', 'performance'],
}
