CONFIGS = {'DEBUG': True,
           'queries_file': r'files/queries_embeddings_v1.pkl',
           'queries_file_v2': r'files/queries_embeddings_v2.pkl',
           'queries_file_v3': r'files/queries_embeddings_v3.pkl',
           'designs_json_file_path': r'files/designs.json',
           'image_loading_timeout': 30,
           'min_split_score':3,
           'max_img_split':2,
           'max_total_spreads':20,
           'max_group_spread':3,
           'max_imges_per_spread':24,
           'min_per_spread': 4,
           'max_per_spread': 38,
           'distance_weight': 10,
           'size_weight': 0.9,
           'split_group_penalty': 0.01,
           'max_size_for_normalize': 44,
           'min_size_for_normalize': 2,
           'split_homogenous_group_penalty': 0.1,
           'crop_penalty': 0.01,
           'color_mix': 0.0001,
           'double_page_color_mix': 0.00000001,
           'class_mix': 0.00001,
           'orientation_mix': 0.1,
           'spread_score_threshold': 0.01,
           'partition_score_threshold': 100,
           'MaxCombs': 1000,
           'MaxCombsLargeGroups': 100,
           'MaxOrientedCombs': 300,
           'top_imges_for_cover' : 3,
           'max_reading_workers':2,
           'cropping_workers':2,
           'max_lay_workers': 1,
           "max_photos_group":12,
           'wedding_merge_images_number':2,
           'collection_name': 'aigeneratealbumdto',
           'visibility_timeout':1200,
           'products_json_location':'pictures/photostore/32/settings/products.json.txt',
           'design_pack_base':'pictures/photostore/32/ext/designs',
           'architect_base':'pictures/photostore/32/ext/productgroups',

           'merge_limit_times': 3,
           'none_limit_times': 5,

            #Qdrant
            "QDRANT_HOST": "10.0.44.13",
            "QDRANT_COLLECTION": {1:"ImageEmbedding_V1",
                                  2:"ImageEmbedding_V2",},
            #mongo DB
            "DB_NAME": "aimongo",
            "STATUS_COLLECTION_NAME": "aiprojectstatusdal",
            "DB_CONNECTION_STRING_VAR": "MongoConnectionString",


           #selection
           'content_threads': 4,
           'small_groups': 3,
           'max_number_images': 130,
           'person_score': 0.0000001,
           'similarity_score': 0.00001,
           'class_matching_zero_score': 0.0001,
           'class_matching_penalty': 0.001,
           'small_groups_not_to_select': 3,
           'grays_scale_limit': 2,
           'person_count_percentage': 0.20,
           'small_gallery_number': 15,
           'events_disallowing_small_images': ['settings', 'vehicle', 'rings', 'food', 'accessories', 'entertainment',
                                               'dancing',
                                               'wedding dress', 'kiss'],
           'total_target_images': 130,
           'layouts': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 24],
           'FACE_FAR_THRESHOLD': 0.4,
           'FACE_M_THRESHOLD': 0.7,
           'BODY_FAR_THRESHOLD': 0.7,
           'BODY_MEDIUM_THRESHOLD': 0.4,
           'ε': 1e-9,
           'focus_csv_path':r'files/focus_csv.csv',
           'bin_name_dictionary':{
                'weddingDress':'wedding_dress',
                'brideGettingReady':'bridegettingready',
                'groomGettingReady':'groomgettingready',
               'tableSetting':'table_setting',
               'holdingHands':'holdinghands',
               'softLight': 'softlight',
           },
        'weights' :{
            'class': 0.2,
            'similarity': 0.2,
            'person': 0.4,
            'tags': 0.1,
            'rank': 0.2
         },
           'density_factors' : {1: 0.5, 2: 0.75, 3: 1, 4: 1.5, 5: 2.0},
        'MAX_PERSON_COMBINATION': 10000,

}

merge_content_priority = {
    'accessories': 0.9,
    'bride': 0.0001,
    'bride and groom': 0.0001,
    'bride getting dressed': 0.5,
    'bride party': 0.3,
    'cake cutting': 0.9,
    'ceremony': 0.0001,
    'couple': 0.0001,
    'dancing': 0.9,
    'detail': 0.91,
    'entertainment': 0.92,
    'first dance': 0.001,
    'food': 0.92,
    'full party': 0.001,
    'getting hair-makeup': 0.92,
    'groom': 0.0001,
    'groom party': 0.3,
    'inside vehicle': 0.92,
    'invite': 0.92,
    'kiss': 0.2,
    'pet': 0.92,
    'portrait': 0.0001,
    'rings': 0.92,
    'settings': 0.92,
    'speech': 0.92,
    'suit': 0.92,
    'vehicle': 0.92,
    'very large group': 0.0001,
    'walking the aisle': 0.0001,
    'wedding dress': 0.92,
    'other': 0.92,
    'nan': 0.92,
}
# Content priority scores
split_content_priority = {
    'accessories': 0.0001,
    'bride': 0.9,
    'bride and groom': 0.9,
    'bride getting dressed': 0.5,
    'bride party': 0.3,
    'cake cutting': 0.001,
    'ceremony': 0.8,
    'couple': 0.7,
    'dancing': 0,
    'detail': 0.001,
    'entertainment': 0.001,
    'first dance': 0.6,
    'food': 0.001,
    'full party': 0.001,
    'getting hair-makeup': 0.001,
    'groom': 0.9,
    'groom party': 0.3,
    'inside vehicle': 0.001,
    'invite': 0.001,
    'kiss': 0.2,
    'pet': 0.001,
    'portrait': 0.02,
    'rings': 0.0001,
    'settings': 0.0001,
    'speech': 0.02,
    'suit': 0.0001,
    'vehicle': 0.0001,
    'very large group': 0.0001,
    'walking the aisle': 0.2,
    'wedding dress': 0.0001,
    'other': 0.000001,
    'nan': 0.00001,
}

relations = {'brideAndGroom':{
    'bride and groom': (10, 0.2),

    'bride': (7, 0.1),
    'groom': (10, 0.001),

    'bride party': (8, 0.5),
    'groom party': (8, 0.5),
    'full party': (4, 0.5),

    'large_portrait': (4, 0.5),
    'small_portrait': (7, 0.5),
    'portrait': (7, 0.1),
    'very large group': (8, 0.5),
    'walking the aisle': (6, 0.4),

    'bride getting dressed': (6, 0.5),
    'first dance': (2, 0.2),
    'cake cutting': (2, 0.1),
    'ceremony': (10, 0.2),
    'couple': (0, 0),
    'dancing': (24, 0.5),

    'entertainment': (0, 0.2),

    'kiss': (2, 0.6),
    'pet': (0, 0.5),

    'accessories': (1, 0.01),
    'settings': (5, 0.1),
    'speech': (4, 0.5),

    'detail': (5, 0.5),
    'getting hair-makeup': (4, 0.1),
    'food': (5, 0.5),
    'other': (0, 0),
    'None':(0,0),
    'invite': (1, 0.5),
    'wedding dress':(2,0.01),
    'vehicle': (2,0.01),
    'inside vehicle':(2,0.01),
    'suit':(1, 0.5),
    'rings':(1,0.5)

},
    'parents': {
        'bride and groom': (8, 0.2),

        'bride': (4, 0.1),
        'groom': (4, 0.001),

        'bride party': (4, 0.5),
        'groom party': (4, 0.5),
        'full party': (4, 0.5),
        'portrait': (10, 0.1),
        'very large group': (10, 0.5),
        'walking the aisle': (4, 0.4),

        'bride getting dressed': (3, 0.5),
        'first dance': (2, 0.2),
        'cake cutting': (2, 0.1),
        'ceremony': (15, 0.2),
        'couple': (0, 0),
        'dancing': (12, 0.5),

        'entertainment': (2, 0.2),

        'kiss': (2, 0.6),
        'pet': (1, 0.5),

        'accessories': (1, 0.01),
        'settings': (8, 0.1),
        'speech': (8, 0.5),

        'detail': (8, 0.5),
        'getting hair-makeup': (2, 0.1),
        'food': (10, 0.5),
        'other': (0, 0.5),
        'invite': (1, 0.5),
        'wedding dress': (2, 0.01),
        'vehicle': (2, 0.01),
        'inside vehicle': (2, 0.01),
        'suit': (0, 0.5),
        'rings': (1, 0.5)

    }
,'everyoneElse':{
    'bride and groom': (15, 0.2),

    'bride': (4, 0.1),
    'groom': (4, 0.001),
    'bride party': (8, 0.5),
    'groom party': (8, 0.5),
    'full party': (6, 0.5),
    'portrait': (5, 0.1),
    'very large group': (6, 0.5),
    'walking the aisle': (10, 0.4),

    'bride getting dressed': (6, 0.5),
    'first dance': (4, 0.2),
    'cake cutting': (4, 0.1),
    'ceremony': (10, 0.2),
    'couple': (0, 0),
    'dancing': (24, 0.5),

    'entertainment': (3, 0.2),

    'kiss': (2, 0.6),
    'pet': (0, 0.5),

    'accessories': (1, 0.01),
    'settings': (5, 0.1),
    'speech': (5, 0.5),

    'detail': (5, 0.5),
    'getting hair-makeup': (4, 0.1),
    'food': (5, 0.5),
    'other': (0, 0.5),
    'invite': (1, 0.5),
    'wedding dress':(1,0.01),
    'vehicle': (1,0.01),
    'inside vehicle':(1,0.01),
    'suit':(1, 0.5),
    'rings': (1, 0.5)

}}


limit_imgs = {
    'bride and groom': 9,

    'bride': 7,
    'groom': 7,

    'bride party': 8,
    'groom party': 8,
    'full party': 4,
    'portrait': 10,
    'very large group': 6,
    'walking the aisle': 7,
    'bride getting dressed': 4,
    'first dance': 5,
    'cake cutting': 5,
    'ceremony': 8,
    'couple': 0,
    'dancing': 24,
    'entertainment': 4,
    'kiss': 6,
    'pet': 2,
    'accessories': 2,
    'settings': 8,
    'speech': 8,
    'detail': 10,
    'getting hair-makeup': 4,
    'food': 6,
    'other':0,
    'invite': 1,
    'wedding dress': 1,
    'rings': 1,
    'vehicle': 1
}

label_list = [
    'accessories',
    'bride',
    'bride and groom',
    'bride getting dressed',
    'bride party',
    'cake cutting',
    'ceremony',
    'couple',
    'dancing',
    'detail',
    'entertainment',
    'first dance',
    'food',
    'full party',
    'getting hair-makeup',
    'groom',
    'groom party',
    'inside vehicle',
    'invite',
    'kiss',
    'pet',
    'portrait',
    'rings',
    'settings',
    'speech',
    'suit',
    'vehicle',
    'very large group',
    'walking the aisle',
    'wedding dress',
    'other',
    'two brides',
    'two grooms',
]

# image selection
spreads_required_per_category = {
    'bride and groom': 2,
    'bride': 2,
    'groom': 2,
    'bride party': 1,
    'groom party': 1,
    'full party': 1,
    'large_portrait': 2,
    'small_portrait': 1,
    'portrait': 1,
    'very large group': 2,
    'walking the aisle': 1,
    'bride getting dressed': 0.5,
    'first dance': 1,
    'cake cutting': 1,
    'ceremony': 1,
    'couple': 0,
    'dancing': 1,
    'entertainment': 1,
    'kiss': 1,
    'pet': 0,
    'accessories':1,
    'settings': 1,
    'speech': 1,
    'detail': 1,
    'getting hair-makeup': 0.5,
    'food': 1,
    'other': 0,
    'invite': 0,
    'None':0,
    'wedding dress': 1,
    'vehicle':0,
    'inside vehicle':0
}

priority_categories = ['bride and groom',
                       'bride','groom','ceremony','bride party',
    'groom party','full party','dancing','large_portrait',
    'portrait','very large group',
    'walking the aisle',
    'first dance','cake cutting','bride getting dressed',
    'couple',
    'entertainment',
    'kiss',
    'pet',
    'accessories',
    'settings',
    'speech',
    'detail',
    'getting hair-makeup',
    'food',
    'invite',
    'wedding dress',
    'vehicle',
    'inside vehicle']


min_images_per_category = {
    'bride and groom': 4,
    'bride': 4,
    'groom': 4,
    'bride party': 3,
    'groom party': 3,
    'full party': 1,
    'large_portrait': 2,
    'small_portrait': 1,
    'portrait': 10,
    'very large group': 2,
    'walking the aisle': 4,
    'bride getting dressed': 2,
    'first dance': 1,
    'cake cutting': 2,
    'ceremony': 8,
    'couple': 0,
    'dancing': 10,
    'entertainment': 1,
    'kiss': 1,
    'pet': 0,
    'accessories': 1,
    'settings': 4,
    'speech': 4,
    'detail': 4,
    'getting hair-makeup': 2,
    'food': 4,
    'other': 0,
    'invite': 1,
    'None': 0,
    'wedding dress': 1,
    'vehicle': 1,
    'inside vehicle': 1,
    'rings':1

}


selection_threshold = {
    'bride and groom': 0.14,
    'bride': 0.3,
    'groom': 0.005,
    'bride party': 0.14,
    'groom party': 0.14,
    'full party': 0.14,
    'portrait': 0.2,
    'very large group': 0.2,
    'walking the aisle': 0.3,
    'bride getting dressed': 0.2,
    'first dance': 0.2,
    'cake cutting': 0.2,
    'ceremony': 0.14,
    'couple': 0.2,
    'dancing': 0.14,
    'entertainment': 0.14,
    'kiss': 0.2,
    'pet': 0.14,
    'accessories':0.5,
    'settings': 0.3,
    'speech': 0.3,
    'detail': 0.3,
    'getting hair-makeup': 0.2,
    'food': 0.2,
    'other': 0.15,
    'invite': 0.15,
    'None':0.15,
    'wedding dress': 0.2,
    'vehicle':0.15,
    'inside vehicle':0.15,
    'rings':0.15,
    'suit':0.15,

}