limit_imgs = {
    'bride and groom': 9,

    'bride': 7,
    'groom': 7,

    'bride party': 8,
    'groom party': 8,
    'full party': 4,
    'portrait': 10,
    'very large group': 6,
    'walking the aisle': 7,
    'bride getting dressed': 4,
    'first dance': 5,
    'cake cutting': 5,
    'ceremony': 8,
    'couple': 0,
    'dancing': 24,
    'entertainment': 4,
    'kiss': 6,
    'pet': 2,
    'accessories': 2,
    'settings': 8,
    'speech': 8,
    'detail': 10,
    'getting hair-makeup': 4,
    'food': 6,
    'other':0,
    'invite': 1,
    'wedding dress': 1,
    'rings': 1
}