category_queries = {
    'bride_preparation_before_wedding': ['bride\'s shoes', 'wedding dress only',
                                         "wedding dress hanging in the wall or something",
                                         "flowers boutique\'s bride Only", 'wedding\'s rings alone',
                                         'wedding rings on the table''bride getting dress', 'bride getting hair done',
                                         'bride getting makeup done', 'bride putting her jewelry',
                                         'bride with her bridesmaid preparing for the wedding',
                                         "bride carrying her wedding dress", "hairdresser is styling bride\'s hair",
                                         "makeup artist putting makeup for the bride",
                                         "bride and bridesmaids in pajamas",
                                         "bride and bridesmaids in pajamas drinking glass of drink",
                                         'A bride\’s bouquet Only'],
    'groom_preparation_before_wedding': ['groom\'s shoes', 'suit cuff', 'suit alone', 'men hand watch alone ',
                                         'someone without face holding wedding\'s rings',
                                         'groom and groomsbestmen preparing before the wedding but not wearing suits',
                                         'groom is getting ready for wedding ', 'groom putting his cufflinks ',
                                         'groom with his groomsmen getting ready for the wedding',
                                         'grooms and his grooms mens trying to put the tie of the suit'],
    'wedding_reception_before_ceremony': [
        'The bride\'s parents welcoming guests with smiles and warmth as they enter the venue.',
        'Guests mingling in anticipation, exchanging greetings and well wishes',
        'groom is welcoming his guests at the door of the hall',
        'guests hugging and gretting grooms before the wedding starts', ],
    'couple_arrival_before_ceremony': ['groom or bride in a vehicle', 'bride and groom in limousine',
                                       'bride and groom standing in front of limousine',
                                       'bride getting outside the car', 'brides has arrived by car',
                                       'bride has arrived to the venue\'s wedding'],
    'wedding_ceremony': ['ceremony of bride and groom', 'wedding ceremony',
                         'bride is doing performance during the ceremony',
                         'bride or groom giving vows exchange during the ceremony',
                         'groom is doing performance during the ceremony',
                         'bride and groom doing special dance in the ceremony'],
    'speech_toasts': ['bridesmaids giving speech', 'one of the brides family giving speech',
                      'one of the grooms family or friends giving a speech at party',
                      'someone giving speech during the wedding after the cermony',
                      'guests and bride and groom making toasts for the speech', 'person standing giving a speech',
                      'everyone holding cups or glasses for toasts', 'person cheering for toasts with wine'],
    'photo_session_bride_and_groom': ["bride and groom sharing a heartfelt laugh",
                                    "a tender moment between newlyweds",
                                    "emotional first look between bride and groom",
                                    "a romantic whisper shared by the bride and groom",
                                    "joyful and candid moment of the bride and groom",
                                    "bride and groom lost in each other's eyes",
                                    "bride and groom golden hour wedding portrait",
                                    "epic sunset silhouette of the bride and groom",
                                    "fine art wedding photography of the bride and groom",
                                    "dramatic lighting on the bride and groom's portrait",
                                    "creative and artistic wedding portrait of the bride and groom",
                                    "timeless black and white portrait of the bride and groom",
                                    "bride and groom alone together after the wedding ceremony",
                                    "an intimate portrait of just the bride and groom",
                                    "a secluded and private photoshoot of the bride and groom",
                                    "a private moment captured between the bride and groom on their wedding day",
                                    "a focused portrait of the bride and groom, with no guests",
                                    "the bride and groom in a world of their own",
                                      ],
    'bride_bridesmaids_photosession': ['photo session brides with her maids after ceremony',
                                       'bride and her bridesmaids holding flowers without showing faces',
                                       'brides with her maids wearing dressings',
                                       'bride and bridesmaids standing for group picture wearing dresses',
                                       'bridesmaids doing party for bride after wedding ceremony wearing all dresses'],
    'groom_bestmen_photosession': ['groom with his best men standing together', 'group photo of groom with his bestmen',
                                   'groom laughing with his friends bestmens'],
    'bride_groom_maids_photosession': ['bride and groom with groommen and bride maids',
                                       "bridemaid and groomen all together next to brde and groom",
                                       "bride and groom with bridemaids and groommen"],
    'dancing': ['bride and groom with bridesmaids and bestsmen dancing', 'celebration of wedding party',
                'everyone is dancing', 'weddings party with colorful lights',
                'everyone laughing and dancing in the wedding party'],
    'special_moments': ['bride and groom in a great moment together',
                        'bride and groom doing a great photosession together',
                        ' bride and groom with a fantastic standing looking to each other with beautiful scene',
                        'Couple with a scenic view', 'bride and groom kissing each other in a photoshot',
                        'bride and groom holding hands', 'bride and groom half hugged for a speical photo moment'],
    'family_portraits': ['bride with her family posing group picture', 'groom with his famikly group posing picture',
                         'family together with bride and groom standing posing for photo',
                         'bride with her parents posing  as a group photo',
                         'groom with his parents standing as posing group'],
    'bride_parents': ['bride with her father before walking the aisle', 'posing photo of bride with her parents only',
                      'bride with her mother only'],
    'groom_parents': ['groom with his father before walking the aisle', 'posing photo of groom with his parents only',
                      'groom  with his mother only'],
    'bride_prepreation_detail_shots': ['bride\'s shoes', 'wedding dress only',
                                       "wedding dress hanging in the wall or something",
                                       "flowers boutique\'s bride Only", 'wedding\'s rings alone',
                                       'wedding rings on the table'],
    'groom_prepreation_detail_shots': ['groom\'s shoes', 'suit cuff', 'suit alone', 'men hand watch alone ',
                                       'someone without face holding wedding\'s rings'],
    'aisle_detail_shots': ['hall decor', 'aisle with flowers', 'asile chairs settings without people',
                           'hall of ceremony'],
    'detail_shots': ['building ', 'venue', 'table setting', 'book glass award', 'Ice Sculpture', 'decor',
                     'invitation letter', 'weddings rings', 'cake cutting without showing faces',
                     'bride and groom cut a cake without showing faces', 'brides shoes or sandals',
                     'empty tables and chairs inside hall', 'pary venue of the wedding', 'flowers and tables empty'],
    'wedding_dinner': ['dinner food on table', 'guests setting around tables having dinner',
                       'food on table and people eating', 'food'],
    'groom_and_bride_first_dance': ['groom and brides dancing together solo', 'first dance of groom and bride',
                                    'bride and groom dancing alone'],
    'walking_down_the_aisle': ['bride with her father walking the aisle', 'groom waiting the bride in the aisle',
                               'groom looking at the bride walking the aisle',
                               'bridesmaid walking with groomsmen in the aisle', 'kids with flowers walking the aisle',
                               'couples walking the aisle', 'couples  holding hands walking down the aisle',
                               'wedding Aisle with couples',
                               'bridemaid holding flower walking with her partner down the aisle',
                               'people setting on organized raw chairs waiting for bride and groom'],
    'party_detail_shots': ['tables of party', 'tables and chairs of the party after the ceremony',
                           'lights in the hall for the party', 'party settings', 'party stage'],
    'cutting_cake': ['bride and groom cutting cake', 'weddings cake has been cutted',
                     'bride and groom feed each other piece of cake'],
    'bride_only_photosession': ['bride only in the picture wearing white dress', 'bride special pose with herself',
                                'bride with potique of flowers only', 'only bride posing in a special way for photo',
                                'bride photosession for her only'],
    'groom_only_photosession': ['groom wearing suit only in the picture', 'groom standing all himself',
                                'there\'s only groom posing speical way for photosession',
                                'a picture of groom only looking at the camera'],
    'kissing': ['groom and bride kissing each other in a romantic way', ' bride and groom kissing in a romantic way',
                'photo of two couples kissing'],
    'vehicle': ['vehicle', 'car', 'bride and groom inside vehicle', 'bride and groom near vehicle'],
    'invite': ['wedding invitation', 'papers of invitation'],
    'pet': ['pet', 'dog', 'cat'],
    'accessories': ['accessories', 'rings', 'braclets']
}

Parts = {
    'accessories': category_queries['accessories'],
    'bride': category_queries['bride_only_photosession'],
    'bride and groom': category_queries['photo_session_bride_and_groom'],
    'bride getting dressed': category_queries['bride_preparation_before_wedding'],
    'bride party': category_queries['bride_bridesmaids_photosession'],
    'groom': category_queries['groom_preparation_before_wedding'] + category_queries['groom_only_photosession'],
    'groom party': category_queries['groom_bestmen_photosession'],
    'full party': category_queries['bride_groom_maids_photosession'],
    'ceremony': category_queries['wedding_ceremony'],
    'dancing': category_queries['dancing'],
    'first dance': category_queries['groom_and_bride_first_dance'],
    'cake cutting': category_queries['cutting_cake'],
    'food': category_queries['wedding_dinner'],
    'inside vehicle': category_queries['vehicle'],
    'invite': category_queries['invite'],
    'kiss': category_queries['kissing'],
    'pet': category_queries['pet'],
    'portrait': category_queries['family_portraits'],
    'walking the aisle': category_queries['walking_down_the_aisle'],
    'settings': category_queries['party_detail_shots'] + category_queries['aisle_detail_shots'] + category_queries[
        'detail_shots'],
    'speech': category_queries['speech_toasts'],

}


# old quieres for bride and groom
# ['bride and groom ONLY', 'bride and groom ONLY with beautiful background ',
#                                       'A personal moment between the groom and bride ONLY',
#                                       ' intimate moment in a serene setting between bride and groom ONLY',
#                                       'A black and white image that adds variety to the photo shoot of bride and groom ONLY',
#                                       'Bride and groom ONLY in a different setting ',
#                                       'Smiling bride and groom are Only in the photo',
#                                       'bride and groom Only in the picture  holding hands',
#                                       'bride and groom Only in a gorgeous standing ',
#                                       'bride and groom Only kissing each other in a romantic way',
#                                       'bride and groom in a great moment together',
#                                       'bride and groom doing a great photosession together',
#                                       ' bride and groom with a fantastic standing looking to each other with beautiful scene',
#                                       'Couple with a scenic view', 'bride and groom kissing each other in a photoshot',
#                                       'bride and groom holding hands',
#                                       'bride and groom half hugged for a speical photo moment']