# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: BGSegmentation.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'BGSegmentation.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x42GSegmentation.proto\"\xef\x05\n!PhotoBGSegmentationMessageWrapper\x12M\n\x02v1\x18\x01 \x01(\x0b\x32?.PhotoBGSegmentationMessageWrapper.PhotoBGSegmentationMessageV1H\x00\x1a\xee\x04\n\x1cPhotoBGSegmentationMessageV1\x12\x14\n\x0cmodelVersion\x18\x01 \x01(\x05\x12\x11\n\taccountId\x18\x02 \x01(\x05\x12\x0f\n\x07storeId\x18\x03 \x01(\x05\x12U\n\x06photos\x18\x04 \x03(\x0b\x32\x45.PhotoBGSegmentationMessageWrapper.PhotoBGSegmentationMessageV1.Photo\x1a\xbc\x03\n\x05Photo\x12\x0f\n\x07photoId\x18\x01 \x01(\x03\x12\x64\n\x0c\x62lobCentroid\x18\x02 \x01(\x0b\x32N.PhotoBGSegmentationMessageWrapper.PhotoBGSegmentationMessageV1.Photo.Centroid\x12\x14\n\x0c\x62lobDiameter\x18\x03 \x01(\x02\x12\x15\n\rflatnessScore\x18\x04 \x01(\x05\x12\x18\n\x10\x63ompositionScore\x18\x05 \x01(\x02\x12\x11\n\tdateTaken\x18\x06 \x01(\x03\x12\x12\n\nsceneOrder\x18\x07 \x01(\x02\x12\x14\n\x0corderInScene\x18\x08 \x01(\x03\x12\x13\n\x0b\x61spectRatio\x18\t \x01(\x02\x12^\n\tcolorEnum\x18\n \x01(\x0e\x32K.PhotoBGSegmentationMessageWrapper.PhotoBGSegmentationMessageV1.Photo.Color\x1a \n\x08\x43\x65ntroid\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\"!\n\x05\x43olor\x12\r\n\tgrayscale\x10\x00\x12\t\n\x05\x63olor\x10\x01\x42\n\n\x08versionsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'BGSegmentation_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PHOTOBGSEGMENTATIONMESSAGEWRAPPER']._serialized_start=25
  _globals['_PHOTOBGSEGMENTATIONMESSAGEWRAPPER']._serialized_end=776
  _globals['_PHOTOBGSEGMENTATIONMESSAGEWRAPPER_PHOTOBGSEGMENTATIONMESSAGEV1']._serialized_start=142
  _globals['_PHOTOBGSEGMENTATIONMESSAGEWRAPPER_PHOTOBGSEGMENTATIONMESSAGEV1']._serialized_end=764
  _globals['_PHOTOBGSEGMENTATIONMESSAGEWRAPPER_PHOTOBGSEGMENTATIONMESSAGEV1_PHOTO']._serialized_start=320
  _globals['_PHOTOBGSEGMENTATIONMESSAGEWRAPPER_PHOTOBGSEGMENTATIONMESSAGEV1_PHOTO']._serialized_end=764
  _globals['_PHOTOBGSEGMENTATIONMESSAGEWRAPPER_PHOTOBGSEGMENTATIONMESSAGEV1_PHOTO_CENTROID']._serialized_start=697
  _globals['_PHOTOBGSEGMENTATIONMESSAGEWRAPPER_PHOTOBGSEGMENTATIONMESSAGEV1_PHOTO_CENTROID']._serialized_end=729
  _globals['_PHOTOBGSEGMENTATIONMESSAGEWRAPPER_PHOTOBGSEGMENTATIONMESSAGEV1_PHOTO_COLOR']._serialized_start=731
  _globals['_PHOTOBGSEGMENTATIONMESSAGEWRAPPER_PHOTOBGSEGMENTATIONMESSAGEV1_PHOTO_COLOR']._serialized_end=764
# @@protoc_insertion_point(module_scope)
