# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ContentCluster.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'ContentCluster.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x43ontentCluster.proto\"\x84\x03\n\x1c\x43ontentClusterMessageWrapper\x12\x43\n\x02v1\x18\x01 \x01(\x0b\x32\x35.ContentClusterMessageWrapper.ContentClusterMessageV1H\x00\x1a\x92\x02\n\x17\x43ontentClusterMessageV1\x12\x11\n\taccountId\x18\x01 \x01(\x05\x12\x0f\n\x07storeId\x18\x02 \x01(\x05\x12K\n\x06photos\x18\x03 \x03(\x0b\x32;.ContentClusterMessageWrapper.ContentClusterMessageV1.Photo\x1a\x85\x01\n\x05Photo\x12\x0f\n\x07photoId\x18\x01 \x01(\x03\x12\x12\n\nimageClass\x18\x02 \x01(\x05\x12\x11\n\tclusterId\x18\x03 \x01(\x05\x12\x14\n\x0c\x63lusterClass\x18\x04 \x01(\x05\x12\x16\n\x0eselectionOrder\x18\x05 \x01(\x05\x12\x16\n\x0eselectionScore\x18\x06 \x01(\x02\x42\n\n\x08versionsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ContentCluster_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CONTENTCLUSTERMESSAGEWRAPPER']._serialized_start=25
  _globals['_CONTENTCLUSTERMESSAGEWRAPPER']._serialized_end=413
  _globals['_CONTENTCLUSTERMESSAGEWRAPPER_CONTENTCLUSTERMESSAGEV1']._serialized_start=127
  _globals['_CONTENTCLUSTERMESSAGEWRAPPER_CONTENTCLUSTERMESSAGEV1']._serialized_end=401
  _globals['_CONTENTCLUSTERMESSAGEWRAPPER_CONTENTCLUSTERMESSAGEV1_PHOTO']._serialized_start=268
  _globals['_CONTENTCLUSTERMESSAGEWRAPPER_CONTENTCLUSTERMESSAGEV1_PHOTO']._serialized_end=401
# @@protoc_insertion_point(module_scope)
