# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: PhotoEmbedding.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'PhotoEmbedding.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14PhotoEmbedding.proto\"\xbf\x02\n\x1cPhotoEmbeddingMessageWrapper\x12\x43\n\x02v1\x18\x01 \x01(\x0b\x32\x35.PhotoEmbeddingMessageWrapper.PhotoEmbeddingMessageV1H\x00\x1a\xcd\x01\n\x17PhotoEmbeddingMessageV1\x12\x14\n\x0cmodelVersion\x18\x01 \x01(\x05\x12\x11\n\taccountId\x18\x02 \x01(\x05\x12\x0f\n\x07storeId\x18\x03 \x01(\x05\x12K\n\x06photos\x18\x04 \x03(\x0b\x32;.PhotoEmbeddingMessageWrapper.PhotoEmbeddingMessageV1.Photo\x1a+\n\x05Photo\x12\x0f\n\x07photoId\x18\x01 \x01(\x03\x12\x11\n\tembedding\x18\x05 \x03(\x02\x42\n\n\x08versionsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'PhotoEmbedding_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PHOTOEMBEDDINGMESSAGEWRAPPER']._serialized_start=25
  _globals['_PHOTOEMBEDDINGMESSAGEWRAPPER']._serialized_end=344
  _globals['_PHOTOEMBEDDINGMESSAGEWRAPPER_PHOTOEMBEDDINGMESSAGEV1']._serialized_start=127
  _globals['_PHOTOEMBEDDINGMESSAGEWRAPPER_PHOTOEMBEDDINGMESSAGEV1']._serialized_end=332
  _globals['_PHOTOEMBEDDINGMESSAGEWRAPPER_PHOTOEMBEDDINGMESSAGEV1_PHOTO']._serialized_start=289
  _globals['_PHOTOEMBEDDINGMESSAGEWRAPPER_PHOTOEMBEDDINGMESSAGEV1_PHOTO']._serialized_end=332
# @@protoc_insertion_point(module_scope)
