# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: SocialCircle.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'SocialCircle.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12SocialCircle.proto\"\xa9\x02\n\x1aSocialCircleMessageWrapper\x12?\n\x02v1\x18\x01 \x01(\x0b\x32\x31.SocialCircleMessageWrapper.SocialCircleMessageV1H\x00\x1a\xbd\x01\n\x15SocialCircleMessageV1\x12\x11\n\taccountId\x18\x01 \x01(\x05\x12\x0f\n\x07storeId\x18\x02 \x01(\x05\x12U\n\rsocialCircles\x18\x03 \x03(\x0b\x32>.SocialCircleMessageWrapper.SocialCircleMessageV1.SocialCircle\x1a)\n\x0cSocialCircle\x12\x19\n\x11identityNumeralId\x18\x01 \x03(\x05\x42\n\n\x08versionsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SocialCircle_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SOCIALCIRCLEMESSAGEWRAPPER']._serialized_start=23
  _globals['_SOCIALCIRCLEMESSAGEWRAPPER']._serialized_end=320
  _globals['_SOCIALCIRCLEMESSAGEWRAPPER_SOCIALCIRCLEMESSAGEV1']._serialized_start=119
  _globals['_SOCIALCIRCLEMESSAGEWRAPPER_SOCIALCIRCLEMESSAGEV1']._serialized_end=308
  _globals['_SOCIALCIRCLEMESSAGEWRAPPER_SOCIALCIRCLEMESSAGEV1_SOCIALCIRCLE']._serialized_start=267
  _globals['_SOCIALCIRCLEMESSAGEWRAPPER_SOCIALCIRCLEMESSAGEV1_SOCIALCIRCLE']._serialized_end=308
# @@protoc_insertion_point(module_scope)
