# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: PersonInfo.proto
# Protobuf Python Version: 5.27.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    0,
    '',
    'PersonInfo.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10PersonInfo.proto\"\xbf\x05\n\x18PersonInfoMessageWrapper\x12;\n\x02v1\x18\x01 \x01(\x0b\x32-.PersonInfoMessageWrapper.PersonInfoMessageV1H\x00\x1a\xd9\x04\n\x13PersonInfoMessageV1\x12J\n\nidentities\x18\x01 \x03(\x0b\x32\x36.PersonInfoMessageWrapper.PersonInfoMessageV1.Identity\x12\x11\n\taccountId\x18\x02 \x01(\x05\x12\x0f\n\x07storeId\x18\x03 \x01(\x05\x12\x19\n\x11\x63lusteringVersion\x18\x04 \x01(\x05\x1a\xb6\x03\n\x08Identity\x12\x19\n\x11identityNumeralId\x18\x01 \x01(\x05\x12U\n\npersonInfo\x18\x02 \x01(\x0b\x32\x41.PersonInfoMessageWrapper.PersonInfoMessageV1.Identity.PersonInfo\x1a\x92\x01\n\nPersonInfo\x12T\n\nimagesInfo\x18\x01 \x03(\x0b\x32@.PersonInfoMessageWrapper.PersonInfoMessageV1.Identity.ImageInfo\x12\x0b\n\x03\x61ge\x18\x02 \x01(\x02\x12\x0e\n\x06gender\x18\x03 \x01(\x05\x12\x11\n\tbestPhoto\x18\x04 \x01(\x03\x1ak\n\tImageInfo\x12\x0f\n\x07photoId\x18\x01 \x01(\x03\x12M\n\x08\x66\x61\x63\x65\x42\x62ox\x18\x06 \x01(\x0b\x32;.PersonInfoMessageWrapper.PersonInfoMessageV1.Identity.BBox\x1a\x36\n\x04\x42\x42ox\x12\n\n\x02x1\x18\x01 \x01(\x02\x12\n\n\x02y1\x18\x02 \x01(\x02\x12\n\n\x02x2\x18\x03 \x01(\x02\x12\n\n\x02y2\x18\x04 \x01(\x02\x42\n\n\x08versionsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'PersonInfo_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PERSONINFOMESSAGEWRAPPER']._serialized_start=21
  _globals['_PERSONINFOMESSAGEWRAPPER']._serialized_end=724
  _globals['_PERSONINFOMESSAGEWRAPPER_PERSONINFOMESSAGEV1']._serialized_start=111
  _globals['_PERSONINFOMESSAGEWRAPPER_PERSONINFOMESSAGEV1']._serialized_end=712
  _globals['_PERSONINFOMESSAGEWRAPPER_PERSONINFOMESSAGEV1_IDENTITY']._serialized_start=274
  _globals['_PERSONINFOMESSAGEWRAPPER_PERSONINFOMESSAGEV1_IDENTITY']._serialized_end=712
  _globals['_PERSONINFOMESSAGEWRAPPER_PERSONINFOMESSAGEV1_IDENTITY_PERSONINFO']._serialized_start=401
  _globals['_PERSONINFOMESSAGEWRAPPER_PERSONINFOMESSAGEV1_IDENTITY_PERSONINFO']._serialized_end=547
  _globals['_PERSONINFOMESSAGEWRAPPER_PERSONINFOMESSAGEV1_IDENTITY_IMAGEINFO']._serialized_start=549
  _globals['_PERSONINFOMESSAGEWRAPPER_PERSONINFOMESSAGEV1_IDENTITY_IMAGEINFO']._serialized_end=656
  _globals['_PERSONINFOMESSAGEWRAPPER_PERSONINFOMESSAGEV1_IDENTITY_BBOX']._serialized_start=658
  _globals['_PERSONINFOMESSAGEWRAPPER_PERSONINFOMESSAGEV1_IDENTITY_BBOX']._serialized_end=712
# @@protoc_insertion_point(module_scope)