# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: PersonVector.proto
# Protobuf Python Version: 5.27.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    0,
    '',
    'PersonVector.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12PersonVector.proto\"\xce\x05\n\x1aPersonVectorMessageWrapper\x12?\n\x02v1\x18\x01 \x01(\x0b\x32\x31.PersonVectorMessageWrapper.PersonVectorMessageV1H\x00\x1a\xe2\x04\n\x15PersonVectorMessageV1\x12G\n\x06photos\x18\x01 \x03(\x0b\x32\x37.PersonVectorMessageWrapper.PersonVectorMessageV1.Photo\x12\x11\n\taccountId\x18\x02 \x01(\x05\x12\x0f\n\x07storeId\x18\x03 \x01(\x05\x12\x18\n\x10\x62odyModelVersion\x18\x04 \x01(\x05\x12\x19\n\x11\x62odyDetectVersion\x18\x05 \x01(\x05\x1a\xa6\x03\n\x05Photo\x12\x0f\n\x07photoId\x18\x01 \x01(\x03\x12L\n\x06\x62odies\x18\x06 \x03(\x0b\x32<.PersonVectorMessageWrapper.PersonVectorMessageV1.Photo.Body\x1a\xd4\x01\n\x04\x42ody\x12\n\n\x02id\x18\x01 \x01(\t\x12J\n\x04\x62\x62ox\x18\x02 \x01(\x0b\x32<.PersonVectorMessageWrapper.PersonVectorMessageV1.Photo.BBox\x12\x0c\n\x04\x63onf\x18\x03 \x01(\x02\x12\x11\n\tembedding\x18\x04 \x01(\x0c\x12S\n\tkeypoints\x18\x05 \x03(\x0b\x32@.PersonVectorMessageWrapper.PersonVectorMessageV1.Photo.Keypoint\x1a\x36\n\x04\x42\x42ox\x12\n\n\x02x1\x18\x01 \x01(\x02\x12\n\n\x02y1\x18\x02 \x01(\x02\x12\n\n\x02x2\x18\x03 \x01(\x02\x12\n\n\x02y2\x18\x04 \x01(\x02\x1a/\n\x08Keypoint\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\r\n\x05score\x18\x03 \x01(\x02\x42\n\n\x08versionsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'PersonVector_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PERSONVECTORMESSAGEWRAPPER']._serialized_start=23
  _globals['_PERSONVECTORMESSAGEWRAPPER']._serialized_end=741
  _globals['_PERSONVECTORMESSAGEWRAPPER_PERSONVECTORMESSAGEV1']._serialized_start=119
  _globals['_PERSONVECTORMESSAGEWRAPPER_PERSONVECTORMESSAGEV1']._serialized_end=729
  _globals['_PERSONVECTORMESSAGEWRAPPER_PERSONVECTORMESSAGEV1_PHOTO']._serialized_start=307
  _globals['_PERSONVECTORMESSAGEWRAPPER_PERSONVECTORMESSAGEV1_PHOTO']._serialized_end=729
  _globals['_PERSONVECTORMESSAGEWRAPPER_PERSONVECTORMESSAGEV1_PHOTO_BODY']._serialized_start=412
  _globals['_PERSONVECTORMESSAGEWRAPPER_PERSONVECTORMESSAGEV1_PHOTO_BODY']._serialized_end=624
  _globals['_PERSONVECTORMESSAGEWRAPPER_PERSONVECTORMESSAGEV1_PHOTO_BBOX']._serialized_start=626
  _globals['_PERSONVECTORMESSAGEWRAPPER_PERSONVECTORMESSAGEV1_PHOTO_BBOX']._serialized_end=680
  _globals['_PERSONVECTORMESSAGEWRAPPER_PERSONVECTORMESSAGEV1_PHOTO_KEYPOINT']._serialized_start=682
  _globals['_PERSONVECTORMESSAGEWRAPPER_PERSONVECTORMESSAGEV1_PHOTO_KEYPOINT']._serialized_end=729
# @@protoc_insertion_point(module_scope)